### ISSUE TITLE
Links and other formatting (e.g. bold, italic, h2...) use the same color

### ISSUE THREAD

**Issue by ruben-sg** [AllJavi/material_gruvbox_obsidian#2]
Hi there, I really love this theme! However, what is slightly irritating: All the links are the same color as some other formatting. For example all the links have the same color as bold text has. I would really love to change the color of links (no matter if external or internal), but I'm rather new to custom css, so I don't really know how to do this.

**Comment by AllJavi** [comment]
I will not update the theme to apply that because I think is just a personal preference. But I can help you to make what you ask on a CSS snippet. You just need to create a new rule to the classes of that formated url and change the params you want:

```css
/* italic url */
.cm.cm-url {
    color: <COLOR> !important;
}

/* bold url */
.cm.cm-url.cm-strong {
    color: <COLOR> !important;
}
```
